### ISSUE TITLE
Using arrow keys

### ISSUE THREAD

**Issue by mathiasrw** [tr1ckydev/bunsh#2]
Using arrow keys gives a ^[[D instead of moving the courser. 

<img width="376" alt="image" src="https://github.com/tr1ckydev/bsh/assets/1063454/4a0af726-f019-4d46-9e86-a852e6424a41">

**Comment by tr1ckydev** [comment]
Are you on linux or macos?
Because prompt doesn't support arrow keys but readline does. But readline behaves super weird right now on windows. Maybe I can implement readline on non-windows platform.

**Comment by mathiasrw** [comment]
Ahh, I should have specified. Im on mac OS -  native terminal.

**Comment by tr1ckydev** [comment]
Fixed in v0.0.4
