### ISSUE TITLE
Output not being outputted

### ISSUE THREAD

**Issue by mathiasrw** [tr1ckydev/bunsh#3]
Using bsh I expect `npx cowsay abc` to provide an output, but nothing is outputted. 

<img width="375" alt="image" src="https://github.com/tr1ckydev/bsh/assets/1063454/4a7a147a-bd51-49bf-aaa3-8054be876693">

**Comment by tr1ckydev** [comment]
![image](https://github.com/tr1ckydev/bsh/assets/86865279/a4d33cf2-8b9e-4914-a9a8-7e4d686d4fb5)
Works now.
